name: "Demo "

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    
    steps:
    - name: Show branch info
      env:
        First_Name: Mona
      run: |
        echo "============================================================================="
        echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        echo "Running on ref: ${GITHUB_REF}"
        echo "Running on ref_name: ${GITHUB_REF_NAME}"
        echo "Running on repository: ${GITHUB_REPOSITORY}"
        echo "============================================================================="
        id
        hostname
        pwd
        ls -al
        cat /etc/os-release
        echo "============================================================================="
        env
        echo "============================================================================="

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check after
      run: |
        id
        hostname
        pwd
        ls -al
        cat /etc/os-release
        docker version