name: "Demo "

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: [ main, develop ]
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    
    steps:
    - name: Show branch info
      env:
        First_Name: Mona
      run: |
        echo "============================================================================="
        echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        echo "Running on ref: ${GITHUB_REF}"
        echo "Running on ref_name: ${GITHUB_REF_NAME}"
        echo "Running on repository: ${GITHUB_REPOSITORY}"
        echo "Running on number: ${GITHUB_RUN_NUMBER}"
        echo "============================================================================="
        id
        hostname
        pwd
        ls -al
        cat /etc/os-release
        echo "============================================================================"
        docker version
        echo "============================================================================="
        env
        echo "============================================================================="

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check after
      run: |
        pwd
        ls -al
        mkdir -p temp
        cd temp

    - name: Check again
      run: |
        pwd
        ls -al

  next:
    runs-on: ubuntu-22.04
    if: not ${{ github.event_name == 'pull_request' }}
    needs: sync
    steps:
    - name: Show branch info
      run: |
        echo "============================================================================="
        echo "Running on ref: ${GITHUB_REF}"
        echo "Running on ref: ${{ github.ref }}"
        
        echo "Running on ref_name: ${GITHUB_REF_NAME}"
        echo "Running on ref_name: ${{ github.ref_name }}"

        echo "Running on repository: ${GITHUB_REPOSITORY}"
        echo "Running on repository: ${{ github.repository }}"

        echo "Running on repositoryUrl: ${GITHUB_REPOSITORY_URL }"
        echo "Running on repositoryUrl: ${{ github.repositoryUrl }}"

        echo "Running on number: ${GITHUB_RUN_NUMBER}"
        echo "Running on number: ${{ github.run_number }}"
        echo "============================================================================="
        env