name: CI

on:
  push:
    
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Show branch info
      run: |
        echo "Running on branch: ${GITHUB_REF}"
        echo "Running on branch: ${GITHUB_REF_NAME}"
        pwd
        ls -al
        id

    - name: Checkout repository
      uses: actions/checkout@v4