name: CI

on:
  push:
    
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Show branch info
      run: |
        echo "Running on ref: ${GITHUB_REF}"
        echo "Running on ref_name: ${GITHUB_REF_NAME}"
        echo "Running on repository: ${GITHUB_REPOSITORY}"
        pwd
        ls -al
        id
        hostname
        cat /etc/os-release

    - name: Checkout repository
      uses: actions/checkout@v4