name: CI

on:
  push:
    
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Show branch info
      run: echo "Running on branch: ${{ github.ref_name }}"

    - name: Checkout repository
      uses: actions/checkout@v4